import type { Metadata } from "next";
import {Jost, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Common/Header";
import Footer from "@/components/Common/Footer";
import { LipstickProvider } from "@/context/ColorContext";
import { SunglassProvider } from "@/context/SunglassContext";

const jost = Jost({
  subsets: ["latin"],
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${jost.className} antialiased`}
      >
        <SunglassProvider>
          <LipstickProvider>
          <Navbar />
             {children}
          <Footer />
        </LipstickProvider>
        </SunglassProvider>
      </body>
    </html>
  );
}
